/*
SQLyog v10.2 
MySQL - 5.0.27-community-nt 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

insert into `destoon_module` (`moduleid`, `module`, `name`, `moduledir`, `domain`, `linkurl`, `style`, `listorder`, `islink`, `ismenu`, `isblank`, `logo`, `disabled`, `installtime`) values('1','destoon','核心','','http://demo.destoon.com/v6.0/','http://www.51meiyu.cn/','','1','0','0','0','0','0','1510808022');
insert into `destoon_module` (`moduleid`, `module`, `name`, `moduledir`, `domain`, `linkurl`, `style`, `listorder`, `islink`, `ismenu`, `isblank`, `logo`, `disabled`, `installtime`) values('2','member','会员','member','','http://www.51meiyu.cn/member/','','96','0','0','0','0','0','1510808022');
insert into `destoon_module` (`moduleid`, `module`, `name`, `moduledir`, `domain`, `linkurl`, `style`, `listorder`, `islink`, `ismenu`, `isblank`, `logo`, `disabled`, `installtime`) values('3','extend','扩展','extend','','http://www.51meiyu.cn/extend/','','0','0','0','0','0','0','1510808022');
insert into `destoon_module` (`moduleid`, `module`, `name`, `moduledir`, `domain`, `linkurl`, `style`, `listorder`, `islink`, `ismenu`, `isblank`, `logo`, `disabled`, `installtime`) values('4','company','培训机构','company','','http://www.51meiyu.cn/company/','','2','0','1','0','0','0','1510808022');
insert into `destoon_module` (`moduleid`, `module`, `name`, `moduledir`, `domain`, `linkurl`, `style`, `listorder`, `islink`, `ismenu`, `isblank`, `logo`, `disabled`, `installtime`) values('5','sell','培训课程','sell','','http://www.51meiyu.cn/sell/','','1','0','1','0','0','0','1510808022');
insert into `destoon_module` (`moduleid`, `module`, `name`, `moduledir`, `domain`, `linkurl`, `style`, `listorder`, `islink`, `ismenu`, `isblank`, `logo`, `disabled`, `installtime`) values('7','quote','行情','quote','','http://www.51meiyu.cn/quote/','','97','0','0','0','0','0','1510808022');
insert into `destoon_module` (`moduleid`, `module`, `name`, `moduledir`, `domain`, `linkurl`, `style`, `listorder`, `islink`, `ismenu`, `isblank`, `logo`, `disabled`, `installtime`) values('8','exhibit','展览演出','exhibit','','http://www.51meiyu.cn/exhibit/','','3','0','1','0','0','0','1510808022');
insert into `destoon_module` (`moduleid`, `module`, `name`, `moduledir`, `domain`, `linkurl`, `style`, `listorder`, `islink`, `ismenu`, `isblank`, `logo`, `disabled`, `installtime`) values('9','job','人才','job','','http://www.51meiyu.cn/job/','','93','0','0','0','0','0','1510808022');
insert into `destoon_module` (`moduleid`, `module`, `name`, `moduledir`, `domain`, `linkurl`, `style`, `listorder`, `islink`, `ismenu`, `isblank`, `logo`, `disabled`, `installtime`) values('10','know','美育问答','know','','http://www.51meiyu.cn/know/','','4','0','1','0','0','0','1510808022');
insert into `destoon_module` (`moduleid`, `module`, `name`, `moduledir`, `domain`, `linkurl`, `style`, `listorder`, `islink`, `ismenu`, `isblank`, `logo`, `disabled`, `installtime`) values('11','special','专题','special','','http://www.51meiyu.cn/special/','','92','0','0','0','0','0','1510808022');
insert into `destoon_module` (`moduleid`, `module`, `name`, `moduledir`, `domain`, `linkurl`, `style`, `listorder`, `islink`, `ismenu`, `isblank`, `logo`, `disabled`, `installtime`) values('12','photo','图库','photo','','http://www.51meiyu.cn/photo/','','91','0','0','0','0','0','1510808022');
insert into `destoon_module` (`moduleid`, `module`, `name`, `moduledir`, `domain`, `linkurl`, `style`, `listorder`, `islink`, `ismenu`, `isblank`, `logo`, `disabled`, `installtime`) values('13','brand','品牌','brand','','http://www.51meiyu.cn/brand/','','94','0','0','0','0','0','1510808022');
insert into `destoon_module` (`moduleid`, `module`, `name`, `moduledir`, `domain`, `linkurl`, `style`, `listorder`, `islink`, `ismenu`, `isblank`, `logo`, `disabled`, `installtime`) values('14','video','美育微视','video','','http://www.51meiyu.cn/video/','','6','0','1','0','0','0','1510808022');
insert into `destoon_module` (`moduleid`, `module`, `name`, `moduledir`, `domain`, `linkurl`, `style`, `listorder`, `islink`, `ismenu`, `isblank`, `logo`, `disabled`, `installtime`) values('15','down','下载','down','','http://www.51meiyu.cn/down/','','89','0','0','0','0','0','1510808022');
insert into `destoon_module` (`moduleid`, `module`, `name`, `moduledir`, `domain`, `linkurl`, `style`, `listorder`, `islink`, `ismenu`, `isblank`, `logo`, `disabled`, `installtime`) values('16','mall','商城','mall','','http://www.51meiyu.cn/mall/','','99','0','0','0','0','0','1510808022');
insert into `destoon_module` (`moduleid`, `module`, `name`, `moduledir`, `domain`, `linkurl`, `style`, `listorder`, `islink`, `ismenu`, `isblank`, `logo`, `disabled`, `installtime`) values('17','group','团购','group','','http://www.51meiyu.cn/group/','','98','0','0','0','0','0','1510808022');
insert into `destoon_module` (`moduleid`, `module`, `name`, `moduledir`, `domain`, `linkurl`, `style`, `listorder`, `islink`, `ismenu`, `isblank`, `logo`, `disabled`, `installtime`) values('18','club','商圈','club','','http://www.51meiyu.cn/club/','','88','0','0','0','0','0','1510808022');
insert into `destoon_module` (`moduleid`, `module`, `name`, `moduledir`, `domain`, `linkurl`, `style`, `listorder`, `islink`, `ismenu`, `isblank`, `logo`, `disabled`, `installtime`) values('21','article','美育头条','news','','http://www.51meiyu.cn/news/','','5','0','1','0','0','0','1510808022');
insert into `destoon_module` (`moduleid`, `module`, `name`, `moduledir`, `domain`, `linkurl`, `style`, `listorder`, `islink`, `ismenu`, `isblank`, `logo`, `disabled`, `installtime`) values('22','info','招商','invest','','http://www.51meiyu.cn/invest/','','95','0','0','0','0','0','1510808022');
