/*
SQLyog v10.2 
MySQL - 5.0.27-community-nt 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

insert into `destoon_category` (`catid`, `moduleid`, `catname`, `style`, `catdir`, `linkurl`, `letter`, `level`, `item`, `property`, `parentid`, `arrparentid`, `child`, `arrchildid`, `listorder`, `template`, `show_template`, `seo_title`, `seo_keywords`, `seo_description`, `group_list`, `group_show`, `group_add`) values('48','21','新闻','','meiyuxinwen','list.php?catid=48','x','1','0','0','0','0','0','48','48','','','新闻','新闻','新闻','','','');
insert into `destoon_category` (`catid`, `moduleid`, `catname`, `style`, `catdir`, `linkurl`, `letter`, `level`, `item`, `property`, `parentid`, `arrparentid`, `child`, `arrchildid`, `listorder`, `template`, `show_template`, `seo_title`, `seo_keywords`, `seo_description`, `group_list`, `group_show`, `group_add`) values('116','21','政策','','zhengce','list.php?catid=116','z','1','0','0','0','0','0','116','116','','','政策','政策','政策','','','');
insert into `destoon_category` (`catid`, `moduleid`, `catname`, `style`, `catdir`, `linkurl`, `letter`, `level`, `item`, `property`, `parentid`, `arrparentid`, `child`, `arrchildid`, `listorder`, `template`, `show_template`, `seo_title`, `seo_keywords`, `seo_description`, `group_list`, `group_show`, `group_add`) values('117','21','美育人物','','meiyurenwu','list.php?catid=117','m','1','0','0','0','0','0','117','117','','','美育人物','美育人物','美育人物','','','');
insert into `destoon_category` (`catid`, `moduleid`, `catname`, `style`, `catdir`, `linkurl`, `letter`, `level`, `item`, `property`, `parentid`, `arrparentid`, `child`, `arrchildid`, `listorder`, `template`, `show_template`, `seo_title`, `seo_keywords`, `seo_description`, `group_list`, `group_show`, `group_add`) values('118','21','美育观点','','meiyuguandian','list.php?catid=118','m','1','0','0','0','0','0','118','118','','','美育观点','美育观点','美育观点','','','');
insert into `destoon_category` (`catid`, `moduleid`, `catname`, `style`, `catdir`, `linkurl`, `letter`, `level`, `item`, `property`, `parentid`, `arrparentid`, `child`, `arrchildid`, `listorder`, `template`, `show_template`, `seo_title`, `seo_keywords`, `seo_description`, `group_list`, `group_show`, `group_add`) values('119','21','社会热点','','shehuiredian','list.php?catid=119','s','1','0','0','0','0','0','119','119','','','社会热点','社会热点','社会热点','','','');
insert into `destoon_category` (`catid`, `moduleid`, `catname`, `style`, `catdir`, `linkurl`, `letter`, `level`, `item`, `property`, `parentid`, `arrparentid`, `child`, `arrchildid`, `listorder`, `template`, `show_template`, `seo_title`, `seo_keywords`, `seo_description`, `group_list`, `group_show`, `group_add`) values('120','21','校园安全','','xiaoyuananquan','list.php?catid=120','x','1','0','0','0','0','0','120','120','','','校园安全','校园安全','校园安全','','','');
