/*
SQLyog v10.2 
MySQL - 5.0.27-community-nt 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

insert into `destoon_category` (`catid`, `moduleid`, `catname`, `style`, `catdir`, `linkurl`, `letter`, `level`, `item`, `property`, `parentid`, `arrparentid`, `child`, `arrchildid`, `listorder`, `template`, `show_template`, `seo_title`, `seo_keywords`, `seo_description`, `group_list`, `group_show`, `group_add`) values('46','4','综合培训','','zonghepeixun','list.php?catid=46','z','1','0','0','0','0','0','46','46','','','综合培训','综合','','','','');
insert into `destoon_category` (`catid`, `moduleid`, `catname`, `style`, `catdir`, `linkurl`, `letter`, `level`, `item`, `property`, `parentid`, `arrparentid`, `child`, `arrchildid`, `listorder`, `template`, `show_template`, `seo_title`, `seo_keywords`, `seo_description`, `group_list`, `group_show`, `group_add`) values('42','4','体育培训','','tiyupeixun','list.php?catid=42','t','1','0','0','0','0','0','42','42','','','体育培训','体育、培训','','','','');
insert into `destoon_category` (`catid`, `moduleid`, `catname`, `style`, `catdir`, `linkurl`, `letter`, `level`, `item`, `property`, `parentid`, `arrparentid`, `child`, `arrchildid`, `listorder`, `template`, `show_template`, `seo_title`, `seo_keywords`, `seo_description`, `group_list`, `group_show`, `group_add`) values('43','4','兴趣培训','','xingqupeixun','list.php?catid=43','x','1','0','0','0','0','0','43','43','','','兴趣','兴趣','','','','');
insert into `destoon_category` (`catid`, `moduleid`, `catname`, `style`, `catdir`, `linkurl`, `letter`, `level`, `item`, `property`, `parentid`, `arrparentid`, `child`, `arrchildid`, `listorder`, `template`, `show_template`, `seo_title`, `seo_keywords`, `seo_description`, `group_list`, `group_show`, `group_add`) values('44','4','科学培训','','kexuepeixun','list.php?catid=44','k','1','0','0','0','0','0','44','44','','','科学培训','','','','','');
insert into `destoon_category` (`catid`, `moduleid`, `catname`, `style`, `catdir`, `linkurl`, `letter`, `level`, `item`, `property`, `parentid`, `arrparentid`, `child`, `arrchildid`, `listorder`, `template`, `show_template`, `seo_title`, `seo_keywords`, `seo_description`, `group_list`, `group_show`, `group_add`) values('45','4','其他','','qita','list.php?catid=45','q','1','0','0','0','0','0','45','45','','','其他','','','','','');
insert into `destoon_category` (`catid`, `moduleid`, `catname`, `style`, `catdir`, `linkurl`, `letter`, `level`, `item`, `property`, `parentid`, `arrparentid`, `child`, `arrchildid`, `listorder`, `template`, `show_template`, `seo_title`, `seo_keywords`, `seo_description`, `group_list`, `group_show`, `group_add`) values('41','4','外语培训','','waiyupeixun','list.php?catid=41','w','1','0','0','0','0','0','41','41','','','外语培训','外语、培训','','','','');
insert into `destoon_category` (`catid`, `moduleid`, `catname`, `style`, `catdir`, `linkurl`, `letter`, `level`, `item`, `property`, `parentid`, `arrparentid`, `child`, `arrchildid`, `listorder`, `template`, `show_template`, `seo_title`, `seo_keywords`, `seo_description`, `group_list`, `group_show`, `group_add`) values('40','4','国学培训','','guoxuepeixun','list.php?catid=40','g','1','0','0','0','0','0','40','40','','','','','','','','');
insert into `destoon_category` (`catid`, `moduleid`, `catname`, `style`, `catdir`, `linkurl`, `letter`, `level`, `item`, `property`, `parentid`, `arrparentid`, `child`, `arrchildid`, `listorder`, `template`, `show_template`, `seo_title`, `seo_keywords`, `seo_description`, `group_list`, `group_show`, `group_add`) values('39','4','舞蹈培训','','wudaopeixun','list.php?catid=39','w','1','0','0','0','0','0','39','39','','','','','','','','');
insert into `destoon_category` (`catid`, `moduleid`, `catname`, `style`, `catdir`, `linkurl`, `letter`, `level`, `item`, `property`, `parentid`, `arrparentid`, `child`, `arrchildid`, `listorder`, `template`, `show_template`, `seo_title`, `seo_keywords`, `seo_description`, `group_list`, `group_show`, `group_add`) values('38','4','美术培训','','meishupeixun','list.php?catid=38','m','1','0','0','0','0','0','38','38','','','美术培训','美术、培训','','','','');
insert into `destoon_category` (`catid`, `moduleid`, `catname`, `style`, `catdir`, `linkurl`, `letter`, `level`, `item`, `property`, `parentid`, `arrparentid`, `child`, `arrchildid`, `listorder`, `template`, `show_template`, `seo_title`, `seo_keywords`, `seo_description`, `group_list`, `group_show`, `group_add`) values('37','4','音乐培训','','yinyuepeixun','list.php?catid=37','p','1','0','0','0','0','0','37','37','','','音乐培训','音乐,培训','','','','');
