/*
SQLyog v10.2 
MySQL - 5.0.27-community-nt 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

insert into `destoon_category` (`catid`, `moduleid`, `catname`, `style`, `catdir`, `linkurl`, `letter`, `level`, `item`, `property`, `parentid`, `arrparentid`, `child`, `arrchildid`, `listorder`, `template`, `show_template`, `seo_title`, `seo_keywords`, `seo_description`, `group_list`, `group_show`, `group_add`) values('35','5','科学','','kexue','list.php?catid=35','k','1','0','0','0','0','0','35','35','','','科学','','','','','');
insert into `destoon_category` (`catid`, `moduleid`, `catname`, `style`, `catdir`, `linkurl`, `letter`, `level`, `item`, `property`, `parentid`, `arrparentid`, `child`, `arrchildid`, `listorder`, `template`, `show_template`, `seo_title`, `seo_keywords`, `seo_description`, `group_list`, `group_show`, `group_add`) values('30','5','舞蹈','','wudao','list.php?catid=30','w','1','0','0','0','0','0','30','30','','','舞蹈','舞蹈，教育','舞蹈，教育','','','');
insert into `destoon_category` (`catid`, `moduleid`, `catname`, `style`, `catdir`, `linkurl`, `letter`, `level`, `item`, `property`, `parentid`, `arrparentid`, `child`, `arrchildid`, `listorder`, `template`, `show_template`, `seo_title`, `seo_keywords`, `seo_description`, `group_list`, `group_show`, `group_add`) values('31','5','国学','','guoxue','list.php?catid=31','g','1','0','0','0','0','0','31','31','','','国学','国学','国学','','','');
insert into `destoon_category` (`catid`, `moduleid`, `catname`, `style`, `catdir`, `linkurl`, `letter`, `level`, `item`, `property`, `parentid`, `arrparentid`, `child`, `arrchildid`, `listorder`, `template`, `show_template`, `seo_title`, `seo_keywords`, `seo_description`, `group_list`, `group_show`, `group_add`) values('32','5','外语','','waiyu','list.php?catid=32','w','1','0','0','0','0','0','32','32','','','外语','外语','','','','');
insert into `destoon_category` (`catid`, `moduleid`, `catname`, `style`, `catdir`, `linkurl`, `letter`, `level`, `item`, `property`, `parentid`, `arrparentid`, `child`, `arrchildid`, `listorder`, `template`, `show_template`, `seo_title`, `seo_keywords`, `seo_description`, `group_list`, `group_show`, `group_add`) values('33','5','体育','','tiyu','list.php?catid=33','t','1','0','0','0','0','0','33','33','','','体育','','','','','');
insert into `destoon_category` (`catid`, `moduleid`, `catname`, `style`, `catdir`, `linkurl`, `letter`, `level`, `item`, `property`, `parentid`, `arrparentid`, `child`, `arrchildid`, `listorder`, `template`, `show_template`, `seo_title`, `seo_keywords`, `seo_description`, `group_list`, `group_show`, `group_add`) values('36','5','其他','','qita','list.php?catid=36','q','1','0','0','0','0','0','36','36','','','其他','','','','','');
insert into `destoon_category` (`catid`, `moduleid`, `catname`, `style`, `catdir`, `linkurl`, `letter`, `level`, `item`, `property`, `parentid`, `arrparentid`, `child`, `arrchildid`, `listorder`, `template`, `show_template`, `seo_title`, `seo_keywords`, `seo_description`, `group_list`, `group_show`, `group_add`) values('34','5','兴趣','','xingqu','list.php?catid=34','x','1','0','0','0','0','0','34','34','','','兴趣','','','','','');
insert into `destoon_category` (`catid`, `moduleid`, `catname`, `style`, `catdir`, `linkurl`, `letter`, `level`, `item`, `property`, `parentid`, `arrparentid`, `child`, `arrchildid`, `listorder`, `template`, `show_template`, `seo_title`, `seo_keywords`, `seo_description`, `group_list`, `group_show`, `group_add`) values('29','5','美术','','meishu','list.php?catid=29','m','1','0','0','0','0','0','29','29','','','美术','美术,教育','美术,教育','','','');
insert into `destoon_category` (`catid`, `moduleid`, `catname`, `style`, `catdir`, `linkurl`, `letter`, `level`, `item`, `property`, `parentid`, `arrparentid`, `child`, `arrchildid`, `listorder`, `template`, `show_template`, `seo_title`, `seo_keywords`, `seo_description`, `group_list`, `group_show`, `group_add`) values('28','5','音乐','','yinle','list.php?catid=28','y','1','0','0','0','0','0','28','28','','','音乐','音乐，教育','音乐，教育','','','');
insert into `destoon_category` (`catid`, `moduleid`, `catname`, `style`, `catdir`, `linkurl`, `letter`, `level`, `item`, `property`, `parentid`, `arrparentid`, `child`, `arrchildid`, `listorder`, `template`, `show_template`, `seo_title`, `seo_keywords`, `seo_description`, `group_list`, `group_show`, `group_add`) values('47','5','烘培','','hongpei','list.php?catid=47','h','1','0','0','34','0,34','0','47','47','','','烘培','烘培','','','','');


